import { designSettings, dom } from './state';
import { GRID_SIZE } from './state';

// ═══════════════════════════════════════════════════════════════
// AI ANALYSIS PROMPT
// ═══════════════════════════════════════════════════════════════

export const ANALYSIS_PROMPT = [
  'You are a pixel-perfect Figma design reconstruction engine. Convert this screenshot into a JSON structure that recreates the design as editable Figma layers.',
  '',
  '# OUTPUT SCHEMA',
  '{"width": number, "height": number, "backgroundColor": "#hex", "elements": [Element, ...]}',
  '',
  'Element = {',
  '  "id": string,',
  '  "type": "frame" | "text" | "image" | "icon" | "ellipse" | "rectangle",',
  '  "name": string,',
  '  "x"?: number, "y"?: number,  // Position relative to PARENT (omit for auto-layout children)',
  '  "width": number, "height": number,',
  '  "children": Element[],  // REQUIRED, use [] if empty',
  '',
  '  // Optional properties:',
  '  "fills"?: [{"type": "SOLID", "color": "#hex", "opacity"?: 0-1} | {"type": "GRADIENT_LINEAR", "gradientStops": [{"position": 0-1, "color": "#hex"}]}],',
  '  "stroke"?: {"color": "#hex", "width": number},',
  '  "cornerRadius"?: number | [topLeft, topRight, bottomRight, bottomLeft],',
  '  "opacity"?: 0-1,  // Element-level transparency',
  '  "clipsContent"?: boolean,',
  '  "effects"?: [{"type": "DROP_SHADOW", "color": "#hex", "opacity": 0-1, "offset": {"x": n, "y": n}, "blur": n, "spread"?: n}],',
  '',
  '  // Auto-layout (for frame containers with flowing children):',
  '  "layoutMode"?: "HORIZONTAL" | "VERTICAL",',
  '  "itemSpacing"?: number,',
  '  "paddingTop"?: n, "paddingRight"?: n, "paddingBottom"?: n, "paddingLeft"?: n,',
  '  "primaryAxisAlignItems"?: "MIN" | "CENTER" | "MAX" | "SPACE_BETWEEN",',
  '  "counterAxisAlignItems"?: "MIN" | "CENTER" | "MAX",',
  '  "layoutSizingHorizontal"?: "FIXED" | "FILL" | "HUG",  // How this element sizes in parent auto-layout',
  '  "layoutSizingVertical"?: "FIXED" | "FILL" | "HUG",',
  '  "layoutPositioning"?: "ABSOLUTE",  // Break out of parent auto-layout flow',
  '',
  '  // Text only:',
  '  "text"?: {',
  '    "content": string, "fontSize": number, "fontWeight": 400|500|600|700, "fontFamily": "Google Font name",',
  '    "color": "#hex", "textAlign"?: "LEFT"|"CENTER"|"RIGHT", "lineHeight"?: number|"AUTO", "letterSpacing"?: number,',
  '    "segments"?: [{"text": string, "fontWeight"?: number, "color"?: "#hex"}]  // Only for mixed-weight text',
  '  },',
  '',
  '  // Image only:',
  '  "imageDescription"?: string,  // Detailed visual description for AI image generation',
  '',
  '  // Icon only:',
  '  "lucideIcon"?: string  // Valid Lucide icon name',
  '}',
  '',
  '# LAYOUT RULES',
  '',
  '## Auto-Layout (use for rows, columns, lists, cards, buttons, navbars)',
  '- Set "layoutMode": "HORIZONTAL" or "VERTICAL" on the parent frame',
  '- Children flow automatically - do NOT set x/y on auto-layout children',
  '- Use "layoutSizingHorizontal": "FILL" for children that stretch to fill width',
  '- Use "layoutSizingVertical": "HUG" for children that shrink-wrap their content',
  '- Text elements in auto-layout: typically "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG"',
  '',
  '## Absolute Positioning (use for overlapping elements, floating badges, decorative elements)',
  '- Set x, y relative to the PARENT frame (not the canvas!)',
  '- Use "layoutPositioning": "ABSOLUTE" if inside an auto-layout parent',
  '',
  '## Nesting Strategy',
  '- Build layouts inside-out: smallest components first, then wrap in containers',
  '- Limit nesting to 2-3 levels where possible',
  '- Each logical group (card, button, section) = one frame with auto-layout',
  '',
  '# ELEMENT RULES',
  '',
  '## Text',
  '- Read EVERY character exactly as shown - accents, punctuation, numbers, special chars',
  '- Preserve original language (do NOT translate)',
  '- Use \\n for line breaks',
  '- NO fills on text elements - color goes in text.color',
  '- MEASURE font sizes precisely relative to the total image height:',
  '  - Small body text: typically 12-16px in a 900px height design',
  '  - Subheadings: typically 18-24px',
  '  - Headings: typically 28-48px',
  '  - Hero text: typically 48-72px',
  '  - SCALE these proportionally to the actual image dimensions',
  '- Detect fontFamily: use the closest Google Font match (Inter, Roboto, Open Sans, Montserrat, Poppins, Lato, etc.)',
  '- MIXED FONT WEIGHT: When a single text block has words with DIFFERENT weights (some bold, some regular),',
  '  use "segments" to define per-word styling. Each segment\'s "text" concatenated must EXACTLY equal "content".',
  '  Example: "Ja fez a manutencao do seu poco este ano?" where "manutencao" and "poco" are bold:',
  '  "segments": [{"text": "Ja fez a "}, {"text": "manutencao", "fontWeight": 700}, {"text": " do seu "}, {"text": "poco", "fontWeight": 700}, {"text": " este ano?"}]',
  '- Only use segments when you detect VISIBLE weight differences. If entire text has uniform weight, do NOT include segments.',
  '- Measure lineHeight precisely - use actual pixel value, not "AUTO"',
  '',
  '## Frames (containers)',
  '- Use for any container: cards, buttons, sections, navbars, rows, columns',
  '- Transparent by default (no fills needed if background shows through)',
  '- Add fills for solid backgrounds, stroke for borders',
  '- Use cornerRadius for rounded elements',
  '',
  '## Images',
  '- Use for photos, illustrations, logos, complex graphics',
  '- "imageDescription": describe the visual content precisely for AI generation',
  '- Include subject, colors, composition, style, mood in the description',
  '',
  '## Icons (Lucide library)',
  'Valid names: message-circle, message-square, mail, phone, send, arrow-right, arrow-left,',
  'arrow-up, arrow-down, chevron-right, chevron-left, chevron-up, chevron-down, plus, minus,',
  'x, check, search, settings, menu, edit, trash-2, share, external-link, instagram, facebook,',
  'twitter, linkedin, youtube, globe, heart, star, home, calendar, clock, bell, zap, sun, moon,',
  'user, play, pause, shopping-cart, download, upload, eye, lock, unlock, image, camera, map-pin',
  '- For brand logos/icons NOT in this list, use type "image" with imageDescription instead',
  '',
  '## Ellipse',
  '- Use for circles and ovals (profile pics, decorative dots, circular buttons)',
  '- Detect the ACTUAL fill color - white circles are #FFFFFF, not gray',
  '',
  '## Rectangle',
  '- Use for simple colored shapes, overlays, dividers',
  '- Semi-transparent overlays: fills with opacity < 1',
  '',
  '## Tables and Structured Data',
  '- NUTRITION TABLES / DATA TABLES: Create an outer VERTICAL frame for the table container with stroke border',
  '  - Each ROW is a HORIZONTAL frame with consistent height and itemSpacing',
  '  - First row = header row with bold text (fontWeight 700) and optional background fill',
  '  - Data cells are text elements with "layoutSizingHorizontal": "FILL" or fixed widths for column alignment',
  '  - Column alignment: numbers RIGHT-aligned ("textAlign": "RIGHT"), labels LEFT-aligned',
  '  - Column widths MUST be CONSISTENT across all rows',
  '  - CRITICAL: read EVERY number precisely - values like "5,9" or "134" must be exact',
  '  - Separator lines between rows: use rectangle elements (height: 1, fills: [{"type": "SOLID", "color": "#E0E0E0"}])',
  '  - Table border: add stroke to the outer container frame',
  '',
  '## Barcodes',
  '- BARCODES (EAN-13, UPC, QR codes): Represent as a frame container',
  '  - The barcode itself: type "image" with imageDescription like "Standard EAN-13 barcode with black vertical lines on white background"',
  '  - Below the barcode image, add a text element with the barcode NUMBER if visible (e.g. "7898883937628")',
  '  - Typical barcode dimensions: width ~200-300px, height ~80-100px',
  '  - Do NOT try to represent individual barcode lines as rectangles',
  '',
  '## Warning Badges and Labels',
  '- WARNING BADGES (like "ALTO EM" / regulatory badges):',
  '  - Use a frame with cornerRadius (often fully rounded = large radius or pill shape)',
  '  - Dark fill background (typically #000000) with white text inside',
  '  - Use HORIZONTAL layoutMode for icon + text badges',
  '  - Preserve all text EXACTLY including accents ("ACUCAR ADICIONADO", "GORDURA SATURADA")',
  '',
  '## Fine Print and Legal Text',
  '- INGREDIENTS lists: Single text element with small fontSize (10-12px)',
  '  - Use \\n for line breaks within the text content',
  '  - Preserve ALL punctuation, commas, chemical names, percentages exactly',
  '  - Bold labels like "INGREDIENTES:" or "ALERGICOS:" should use segments with fontWeight 700',
  '- ALLERGEN warnings: Text with specific bold segments for allergen names',
  '- Manufacturer details: Small text, preserve addresses, CNPJ numbers, phone numbers exactly',
  '',
  '## Circular and Non-Rectangular Layouts',
  '- CIRCULAR LABELS: Use a frame with clipsContent: true and cornerRadius equal to width/2 for perfect circle',
  '- Position internal elements using auto-layout or absolute positioning relative to the circle frame',
  '- Curved text: approximate with horizontal text positioned at the correct location',
  '- Use ellipse type for decorative circular elements or backgrounds',
  '',
  '# VISUAL ANALYSIS PROCESS',
  '',
  '1. IDENTIFY the content type (UI, ad, recipe, infographic, landing page, etc.)',
  '2. EXTRACT all text character-by-character in the original language',
  '3. MAP the z-order: background layers FIRST in elements array, foreground LAST',
  '4. DETECT layout patterns: rows → HORIZONTAL, columns → VERTICAL, overlapping → absolute',
  '5. MEASURE dimensions and spacing precisely in pixels:',
  '   - Compare text sizes to total width/height ratio',
  '   - Heading text should be proportionally larger than body text',
  '   - Preserve exact spacing gaps between elements',
  '6. DETECT colors: exact hex values for fills, strokes, text',
  '7. IDENTIFY borders/strokes on any element with visible edges',
  '',
  '# COMPLETE EXAMPLE',
  'Social media ad with background image, overlay, and CTA button:',
  '{',
  '  "width": 1080, "height": 1350, "backgroundColor": "#1A1A1A",',
  '  "elements": [',
  '    {"id": "bg", "type": "image", "name": "Background", "x": 0, "y": 0, "width": 1080, "height": 1350, "imageDescription": "Solar panels on rooftop under clear blue sky with sun flare", "children": []},',
  '    {"id": "overlay", "type": "rectangle", "name": "Dark Overlay", "x": 0, "y": 0, "width": 1080, "height": 1350, "fills": [{"type": "SOLID", "color": "#000000", "opacity": 0.4}], "children": []},',
  '    {"id": "content", "type": "frame", "name": "Content", "x": 60, "y": 200, "width": 960, "height": 900,',
  '      "layoutMode": "VERTICAL", "itemSpacing": 24, "counterAxisAlignItems": "MIN",',
  '      "children": [',
  '        {"id": "title", "type": "text", "name": "Title", "width": 800, "height": 200, "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG", "text": {"content": "Economize ate\\n95% na conta\\nde energia", "fontSize": 56, "fontWeight": 700, "fontFamily": "Montserrat", "color": "#FFFFFF", "lineHeight": 64}, "children": []},',
  '        {"id": "subtitle", "type": "text", "name": "Subtitle", "width": 600, "height": 30, "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG", "text": {"content": "Energia solar residencial e comercial", "fontSize": 20, "fontWeight": 400, "fontFamily": "Montserrat", "color": "#E0E0E0"}, "children": []},',
  '        {"id": "cta", "type": "frame", "name": "CTA Button", "width": 280, "height": 56, "cornerRadius": 12, "fills": [{"type": "SOLID", "color": "#F59E0B"}], "layoutMode": "HORIZONTAL", "itemSpacing": 10, "paddingLeft": 20, "paddingRight": 20, "primaryAxisAlignItems": "CENTER", "counterAxisAlignItems": "CENTER",',
  '          "children": [',
  '            {"id": "ctaIcon", "type": "icon", "name": "Chat", "lucideIcon": "message-circle", "width": 22, "height": 22, "fills": [{"type": "SOLID", "color": "#FFFFFF"}], "children": []},',
  '            {"id": "ctaText", "type": "text", "name": "CTA Label", "width": 150, "height": 24, "text": {"content": "Fale Conosco", "fontSize": 18, "fontWeight": 600, "fontFamily": "Montserrat", "color": "#FFFFFF"}, "children": []}',
  '          ]',
  '        }',
  '      ]',
  '    }',
  '  ]',
  '}',
  '',
  '# EXAMPLE 2 — Login Form',
  'Centered card with email/password inputs, a primary login button, and a signup link:',
  '{',
  '  "width": 480, "height": 640, "backgroundColor": "#F3F4F6",',
  '  "elements": [',
  '    {"id": "card", "type": "frame", "name": "Login Card", "x": 40, "y": 80, "width": 400, "height": 480, "cornerRadius": 16, "fills": [{"type": "SOLID", "color": "#FFFFFF"}], "effects": [{"type": "DROP_SHADOW", "color": "#000000", "opacity": 0.08, "offset": {"x": 0, "y": 4}, "blur": 24}],',
  '      "layoutMode": "VERTICAL", "itemSpacing": 20, "paddingTop": 40, "paddingRight": 36, "paddingBottom": 40, "paddingLeft": 36, "counterAxisAlignItems": "CENTER",',
  '      "children": [',
  '        {"id": "heading", "type": "text", "name": "Heading", "width": 328, "height": 36, "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG", "text": {"content": "Welcome back", "fontSize": 28, "fontWeight": 700, "fontFamily": "Inter", "color": "#111827", "textAlign": "CENTER"}, "children": []},',
  '        {"id": "subtitle", "type": "text", "name": "Subtitle", "width": 328, "height": 20, "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG", "text": {"content": "Sign in to your account", "fontSize": 14, "fontWeight": 400, "fontFamily": "Inter", "color": "#6B7280", "textAlign": "CENTER"}, "children": []},',
  '        {"id": "emailField", "type": "frame", "name": "Email Input", "width": 328, "height": 48, "cornerRadius": 8, "fills": [{"type": "SOLID", "color": "#FFFFFF"}], "stroke": {"color": "#D1D5DB", "width": 1}, "layoutMode": "HORIZONTAL", "paddingLeft": 14, "paddingRight": 14, "primaryAxisAlignItems": "MIN", "counterAxisAlignItems": "CENTER", "layoutSizingHorizontal": "FILL",',
  '          "children": [',
  '            {"id": "emailPlaceholder", "type": "text", "name": "Email Placeholder", "width": 200, "height": 20, "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG", "text": {"content": "you@example.com", "fontSize": 14, "fontWeight": 400, "fontFamily": "Inter", "color": "#9CA3AF"}, "children": []}',
  '          ]',
  '        },',
  '        {"id": "passwordField", "type": "frame", "name": "Password Input", "width": 328, "height": 48, "cornerRadius": 8, "fills": [{"type": "SOLID", "color": "#FFFFFF"}], "stroke": {"color": "#D1D5DB", "width": 1}, "layoutMode": "HORIZONTAL", "paddingLeft": 14, "paddingRight": 14, "primaryAxisAlignItems": "MIN", "counterAxisAlignItems": "CENTER", "layoutSizingHorizontal": "FILL",',
  '          "children": [',
  '            {"id": "passwordPlaceholder", "type": "text", "name": "Password Placeholder", "width": 200, "height": 20, "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG", "text": {"content": "Password", "fontSize": 14, "fontWeight": 400, "fontFamily": "Inter", "color": "#9CA3AF"}, "children": []},',
  '            {"id": "eyeIcon", "type": "icon", "name": "Toggle Password", "lucideIcon": "eye", "width": 20, "height": 20, "fills": [{"type": "SOLID", "color": "#9CA3AF"}], "children": []}',
  '          ]',
  '        },',
  '        {"id": "loginBtn", "type": "frame", "name": "Login Button", "width": 328, "height": 48, "cornerRadius": 10, "fills": [{"type": "SOLID", "color": "#4F46E5"}], "layoutMode": "HORIZONTAL", "primaryAxisAlignItems": "CENTER", "counterAxisAlignItems": "CENTER", "layoutSizingHorizontal": "FILL",',
  '          "children": [',
  '            {"id": "loginLabel", "type": "text", "name": "Button Label", "width": 60, "height": 20, "text": {"content": "Sign In", "fontSize": 16, "fontWeight": 600, "fontFamily": "Inter", "color": "#FFFFFF"}, "children": []}',
  '          ]',
  '        },',
  '        {"id": "signupLink", "type": "text", "name": "Signup Link", "width": 328, "height": 18, "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG", "text": {"content": "Don\'t have an account? Sign up", "fontSize": 13, "fontWeight": 400, "fontFamily": "Inter", "color": "#6B7280", "textAlign": "CENTER", "segments": [{"text": "Don\'t have an account? "}, {"text": "Sign up", "fontWeight": 600, "color": "#4F46E5"}]}, "children": []}',
  '      ]',
  '    }',
  '  ]',
  '}',
  '',
  '# EXAMPLE 3 — Dashboard Stats Card',
  'A row of three metric cards showing KPIs with icons, values, and trend indicators:',
  '{',
  '  "width": 960, "height": 160, "backgroundColor": "#F9FAFB",',
  '  "elements": [',
  '    {"id": "row", "type": "frame", "name": "Stats Row", "x": 0, "y": 0, "width": 960, "height": 160, "layoutMode": "HORIZONTAL", "itemSpacing": 24, "paddingTop": 16, "paddingRight": 16, "paddingBottom": 16, "paddingLeft": 16,',
  '      "children": [',
  '        {"id": "card1", "type": "frame", "name": "Revenue Card", "width": 288, "height": 128, "cornerRadius": 12, "fills": [{"type": "SOLID", "color": "#FFFFFF"}], "stroke": {"color": "#E5E7EB", "width": 1}, "layoutMode": "VERTICAL", "itemSpacing": 8, "paddingTop": 20, "paddingRight": 20, "paddingBottom": 20, "paddingLeft": 20, "layoutSizingHorizontal": "FILL",',
  '          "children": [',
  '            {"id": "c1Header", "type": "frame", "name": "Card1 Header", "width": 248, "height": 20, "layoutMode": "HORIZONTAL", "itemSpacing": 8, "counterAxisAlignItems": "CENTER", "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG",',
  '              "children": [',
  '                {"id": "c1Icon", "type": "icon", "name": "Revenue Icon", "lucideIcon": "zap", "width": 18, "height": 18, "fills": [{"type": "SOLID", "color": "#F59E0B"}], "children": []},',
  '                {"id": "c1Label", "type": "text", "name": "Revenue Label", "width": 180, "height": 18, "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG", "text": {"content": "Total Revenue", "fontSize": 13, "fontWeight": 500, "fontFamily": "Inter", "color": "#6B7280"}, "children": []}',
  '              ]',
  '            },',
  '            {"id": "c1Value", "type": "text", "name": "Revenue Value", "width": 248, "height": 32, "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG", "text": {"content": "$48,560", "fontSize": 28, "fontWeight": 700, "fontFamily": "Inter", "color": "#111827"}, "children": []},',
  '            {"id": "c1Trend", "type": "text", "name": "Revenue Trend", "width": 248, "height": 16, "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG", "text": {"content": "+12.5% from last month", "fontSize": 12, "fontWeight": 500, "fontFamily": "Inter", "color": "#10B981"}, "children": []}',
  '          ]',
  '        },',
  '        {"id": "card2", "type": "frame", "name": "Users Card", "width": 288, "height": 128, "cornerRadius": 12, "fills": [{"type": "SOLID", "color": "#FFFFFF"}], "stroke": {"color": "#E5E7EB", "width": 1}, "layoutMode": "VERTICAL", "itemSpacing": 8, "paddingTop": 20, "paddingRight": 20, "paddingBottom": 20, "paddingLeft": 20, "layoutSizingHorizontal": "FILL",',
  '          "children": [',
  '            {"id": "c2Header", "type": "frame", "name": "Card2 Header", "width": 248, "height": 20, "layoutMode": "HORIZONTAL", "itemSpacing": 8, "counterAxisAlignItems": "CENTER", "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG",',
  '              "children": [',
  '                {"id": "c2Icon", "type": "icon", "name": "Users Icon", "lucideIcon": "user", "width": 18, "height": 18, "fills": [{"type": "SOLID", "color": "#6366F1"}], "children": []},',
  '                {"id": "c2Label", "type": "text", "name": "Users Label", "width": 180, "height": 18, "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG", "text": {"content": "Active Users", "fontSize": 13, "fontWeight": 500, "fontFamily": "Inter", "color": "#6B7280"}, "children": []}',
  '              ]',
  '            },',
  '            {"id": "c2Value", "type": "text", "name": "Users Value", "width": 248, "height": 32, "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG", "text": {"content": "2,340", "fontSize": 28, "fontWeight": 700, "fontFamily": "Inter", "color": "#111827"}, "children": []},',
  '            {"id": "c2Trend", "type": "text", "name": "Users Trend", "width": 248, "height": 16, "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG", "text": {"content": "+8.1% from last month", "fontSize": 12, "fontWeight": 500, "fontFamily": "Inter", "color": "#10B981"}, "children": []}',
  '          ]',
  '        },',
  '        {"id": "card3", "type": "frame", "name": "Bounce Rate Card", "width": 288, "height": 128, "cornerRadius": 12, "fills": [{"type": "SOLID", "color": "#FFFFFF"}], "stroke": {"color": "#E5E7EB", "width": 1}, "layoutMode": "VERTICAL", "itemSpacing": 8, "paddingTop": 20, "paddingRight": 20, "paddingBottom": 20, "paddingLeft": 20, "layoutSizingHorizontal": "FILL",',
  '          "children": [',
  '            {"id": "c3Header", "type": "frame", "name": "Card3 Header", "width": 248, "height": 20, "layoutMode": "HORIZONTAL", "itemSpacing": 8, "counterAxisAlignItems": "CENTER", "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG",',
  '              "children": [',
  '                {"id": "c3Icon", "type": "icon", "name": "Bounce Icon", "lucideIcon": "arrow-down", "width": 18, "height": 18, "fills": [{"type": "SOLID", "color": "#EF4444"}], "children": []},',
  '                {"id": "c3Label", "type": "text", "name": "Bounce Label", "width": 180, "height": 18, "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG", "text": {"content": "Bounce Rate", "fontSize": 13, "fontWeight": 500, "fontFamily": "Inter", "color": "#6B7280"}, "children": []}',
  '              ]',
  '            },',
  '            {"id": "c3Value", "type": "text", "name": "Bounce Value", "width": 248, "height": 32, "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG", "text": {"content": "24.3%", "fontSize": 28, "fontWeight": 700, "fontFamily": "Inter", "color": "#111827"}, "children": []},',
  '            {"id": "c3Trend", "type": "text", "name": "Bounce Trend", "width": 248, "height": 16, "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG", "text": {"content": "-3.2% from last month", "fontSize": 12, "fontWeight": 500, "fontFamily": "Inter", "color": "#EF4444"}, "children": []}',
  '          ]',
  '        }',
  '      ]',
  '    }',
  '  ]',
  '}',
  '',
  '# EXAMPLE 4 — Landing Page Hero Section',
  'Full-width hero with gradient background, large headline, description, CTA button, and a feature image:',
  '{',
  '  "width": 1440, "height": 720, "backgroundColor": "#0F172A",',
  '  "elements": [',
  '    {"id": "heroBg", "type": "rectangle", "name": "Gradient Background", "x": 0, "y": 0, "width": 1440, "height": 720, "fills": [{"type": "GRADIENT_LINEAR", "gradientStops": [{"position": 0, "color": "#0F172A"}, {"position": 1, "color": "#1E3A5F"}]}], "children": []},',
  '    {"id": "heroContent", "type": "frame", "name": "Hero Layout", "x": 0, "y": 0, "width": 1440, "height": 720, "layoutMode": "HORIZONTAL", "itemSpacing": 60, "paddingTop": 100, "paddingRight": 120, "paddingBottom": 100, "paddingLeft": 120, "counterAxisAlignItems": "CENTER",',
  '      "children": [',
  '        {"id": "textCol", "type": "frame", "name": "Text Column", "width": 560, "height": 520, "layoutMode": "VERTICAL", "itemSpacing": 24, "primaryAxisAlignItems": "CENTER", "counterAxisAlignItems": "MIN", "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "FILL",',
  '          "children": [',
  '            {"id": "badge", "type": "frame", "name": "Badge", "width": 140, "height": 32, "cornerRadius": 16, "fills": [{"type": "SOLID", "color": "#1E40AF", "opacity": 0.3}], "layoutMode": "HORIZONTAL", "paddingLeft": 14, "paddingRight": 14, "primaryAxisAlignItems": "CENTER", "counterAxisAlignItems": "CENTER", "layoutSizingVertical": "HUG",',
  '              "children": [',
  '                {"id": "badgeText", "type": "text", "name": "Badge Label", "width": 100, "height": 16, "text": {"content": "Now in Beta", "fontSize": 12, "fontWeight": 600, "fontFamily": "Inter", "color": "#93C5FD"}, "children": []}',
  '              ]',
  '            },',
  '            {"id": "heroTitle", "type": "text", "name": "Hero Title", "width": 560, "height": 144, "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG", "text": {"content": "Build faster with\\nAI-powered tools", "fontSize": 56, "fontWeight": 700, "fontFamily": "Inter", "color": "#F8FAFC", "lineHeight": 68}, "children": []},',
  '            {"id": "heroDesc", "type": "text", "name": "Hero Description", "width": 480, "height": 52, "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG", "text": {"content": "Ship products 10x faster. Our platform automates repetitive tasks so your team can focus on what matters.", "fontSize": 18, "fontWeight": 400, "fontFamily": "Inter", "color": "#94A3B8", "lineHeight": 28}, "children": []},',
  '            {"id": "ctaRow", "type": "frame", "name": "CTA Row", "width": 360, "height": 52, "layoutMode": "HORIZONTAL", "itemSpacing": 16, "counterAxisAlignItems": "CENTER", "layoutSizingVertical": "HUG",',
  '              "children": [',
  '                {"id": "primaryBtn", "type": "frame", "name": "Primary CTA", "width": 170, "height": 52, "cornerRadius": 10, "fills": [{"type": "SOLID", "color": "#3B82F6"}], "layoutMode": "HORIZONTAL", "primaryAxisAlignItems": "CENTER", "counterAxisAlignItems": "CENTER",',
  '                  "children": [',
  '                    {"id": "primaryLabel", "type": "text", "name": "Primary Label", "width": 100, "height": 20, "text": {"content": "Get Started", "fontSize": 16, "fontWeight": 600, "fontFamily": "Inter", "color": "#FFFFFF"}, "children": []}',
  '                  ]',
  '                },',
  '                {"id": "secondaryBtn", "type": "frame", "name": "Secondary CTA", "width": 160, "height": 52, "cornerRadius": 10, "fills": [{"type": "SOLID", "color": "#FFFFFF", "opacity": 0.1}], "stroke": {"color": "#475569", "width": 1}, "layoutMode": "HORIZONTAL", "itemSpacing": 8, "primaryAxisAlignItems": "CENTER", "counterAxisAlignItems": "CENTER",',
  '                  "children": [',
  '                    {"id": "secLabel", "type": "text", "name": "Secondary Label", "width": 80, "height": 20, "text": {"content": "Watch Demo", "fontSize": 16, "fontWeight": 500, "fontFamily": "Inter", "color": "#CBD5E1"}, "children": []},',
  '                    {"id": "playIcon", "type": "icon", "name": "Play Icon", "lucideIcon": "play", "width": 18, "height": 18, "fills": [{"type": "SOLID", "color": "#CBD5E1"}], "children": []}',
  '                  ]',
  '                }',
  '              ]',
  '            }',
  '          ]',
  '        },',
  '        {"id": "heroImage", "type": "image", "name": "Hero Image", "width": 520, "height": 520, "cornerRadius": 16, "layoutSizingHorizontal": "FILL", "imageDescription": "3D isometric illustration of a laptop with floating UI components, charts, and colorful gradient shapes on a dark background", "children": []}',
  '      ]',
  '    }',
  '  ]',
  '}',
  '',
  '# STRICT RULES',
  '1. TEXT MUST BE EXACT - copy every character as shown, preserve language',
  '2. NO fills on text - color goes in text.color only',
  '3. POSITIONS RELATIVE TO PARENT - not the canvas',
  '4. AUTO-LAYOUT children: no x/y, use layoutSizingHorizontal/Vertical',
  '5. TEXT IN AUTO-LAYOUT: MUST have "layoutSizingHorizontal": "FILL", "layoutSizingVertical": "HUG" - NEVER use narrow fixed widths for text',
  '6. Z-ORDER: elements array order = back to front',
  '7. Every element MUST have "children": [] even if empty',
  '8. DETECT ALL STROKES: add stroke for any visible border/outline',
  '9. TRANSPARENT FRAMES: Omit fills for frames where background shows through',
  '10. Use auto-layout as the DEFAULT - only use absolute positioning for overlapping elements',
  '11. MIXED-WEIGHT TEXT: Use "segments" when text has visible bold/regular differences. Segments text MUST concatenate to equal content exactly.',
  '',
  'Return ONLY valid JSON. No explanations, no code blocks.',
].join('\n');

// Helper to get the prompt with user settings injected
export const getAnalysisPrompt = (): string => {
  const basePrompt = ANALYSIS_PROMPT;

  // Only inject user settings if the Design Overrides toggle is ON
  if (!dom.designSettingsPanel || !dom.designSettingsPanel.classList.contains('enabled')) {
    return basePrompt;
  }

  // Build user settings section
  const userSettings: string[] = [];

  userSettings.push('');
  userSettings.push('═══════════════════════════════════════════════════════════════');
  userSettings.push('# USER DESIGN PREFERENCES (IMPORTANT!)');
  userSettings.push('═══════════════════════════════════════════════════════════════');
  userSettings.push('');

  // Font family preference
  if (designSettings.selectedFontFamily) {
    userSettings.push('## FONT FAMILY');
    userSettings.push('The user has specified this Google Font for all text: ' + designSettings.selectedFontFamily);
    userSettings.push('Use "' + designSettings.selectedFontFamily + '" for ALL text elements\' fontFamily property.');
    userSettings.push('');
  }

  // Brand colors
  if (designSettings.brandColors.length > 0) {
    userSettings.push('## BRAND COLORS (User extracted from screenshot)');
    userSettings.push('Match detected colors to these brand HEX values: ' + designSettings.brandColors.join(', '));
    userSettings.push('When you detect a color in the screenshot that is similar to one of these,');
    userSettings.push('use the EXACT brand color HEX value instead of the detected color.');
    userSettings.push('');
  }

  // 4px grid system
  if (designSettings.enableGridSystem) {
    userSettings.push('## ' + GRID_SIZE + '-PIXEL GRID DESIGN SYSTEM (CRITICAL!)');
    userSettings.push('ALL dimensions MUST be multiples of ' + GRID_SIZE + ':');
    userSettings.push(
      '- Widths/heights: 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 48, 56, 64, 80, 96, 120, 160, 200, 240, 320, 400, 480'
    );
    userSettings.push('- Spacing/padding: 4, 8, 12, 16, 20, 24, 32, 40, 48');
    userSettings.push('- Font sizes: 10, 12, 14, 16, 18, 20, 24, 28, 32, 36, 40, 48, 56, 64');
    userSettings.push('- Corner radius: 0, 4, 8, 12, 16, 20, 24');
    userSettings.push('- x, y positions should also snap to ' + GRID_SIZE + 'px grid');
    userSettings.push('Round ALL measurements to the nearest ' + GRID_SIZE + 'px value.');
    userSettings.push('');
  }

  // Custom user instructions
  if (designSettings.customPrompt && designSettings.customPrompt.trim()) {
    userSettings.push('## USER INSTRUCTIONS (Follow these closely!)');
    userSettings.push(designSettings.customPrompt.trim());
    userSettings.push('');
  }

  // If no custom settings, just return base prompt
  if (userSettings.length <= 6) {
    return basePrompt;
  }

  // Insert user settings at the end of the prompt
  return basePrompt + '\n' + userSettings.join('\n');
};
