/**
 * Figmento Tool Definitions for Anthropic API tool_use format.
 * These mirror the MCP server tools but formatted as JSON Schema for the Messages API.
 * Excludes connect_to_figma and disconnect_from_figma (not needed inside the plugin).
 *
 * GENERATED_TOOLS (35 MCP tools) are auto-generated by scripts/generate-tool-schemas.ts.
 * Run `npm run build` (or the prebuild hook) to regenerate tools-schema.generated.ts.
 */

import { GENERATED_TOOLS } from './tools-schema.generated';

export interface ToolDefinition {
  name: string;
  description: string;
  input_schema: Record<string, unknown>;
}

const fillSchema = {
  type: 'object',
  properties: {
    type: { type: 'string', enum: ['SOLID', 'GRADIENT_LINEAR'] },
    color: { type: 'string', description: 'Hex color (e.g. "#FF5733")' },
    opacity: { type: 'number' },
    gradientStops: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          position: { type: 'number' },
          color: { type: 'string' },
          opacity: { type: 'number' },
        },
        required: ['position', 'color'],
      },
    },
    gradientDirection: {
      type: 'string',
      enum: ['left-right', 'right-left', 'top-bottom', 'bottom-top'],
      description: 'Gradient direction (default: top-bottom)',
    },
  },
  required: ['type'],
};

const cornerRadiusSchema = {
  oneOf: [
    { type: 'number' },
    { type: 'array', items: { type: 'number' }, minItems: 4, maxItems: 4 },
  ],
};

// ═══════════════════════════════════════════════════════════════
// PHASE-BASED TOOL FILTERING (Chat mode)
// ═══════════════════════════════════════════════════════════════

/** Tools never sent in chat mode — MCP-only or irrelevant for iterative chat. */
const CHAT_EXCLUDED = new Set([
  'export_node',
  'create_design',
]);

/** Lookup tools — needed in plan phase, removed once design starts. */
const LOOKUP_TOOLS = new Set([
  'get_design_guidance',       // TC-1 consolidated name
  'get_layout_blueprint',
  'get_color_palette',         // backward compat until TC-3
  'get_font_pairing',         // backward compat until TC-3
  'get_size_preset',           // backward compat until TC-3
]);

/** Tools that signal we've entered the build phase. */
const BUILD_PHASE_TRIGGERS = new Set([
  'create_frame',
  'create_text',
  'create_rectangle',
  'create_ellipse',
  'create_image',
  'set_style',                 // TC-1 consolidated name
  'set_fill',                  // backward compat until TC-3
  'set_auto_layout',
]);

/** Plan phase: lookups + basic creation + scene queries. */
const PLAN_PHASE_TOOLS = new Set([
  // Lookups (TC-1 consolidated + backward compat)
  'get_design_guidance',
  'get_layout_blueprint', 'get_color_palette', 'get_font_pairing', 'get_size_preset',
  'get_contrast_check', 'get_design_rules',
  // Intelligence & pairing
  'get_design_intelligence', 'suggest_font_pairing', 'generate_accessible_palette',
  // Scene queries
  'get_selection', 'get_page_nodes', 'get_node_info', 'analyze_canvas_context',
  'scan_frame_structure', 'get_screenshot', 'read_figma_context',
  // Basic creation
  'create_frame', 'create_text', 'create_rectangle', 'create_ellipse',
  // Essential styling (TC-1 consolidated + backward compat)
  'set_style', 'set_fill',
  // Image + utility
  'create_image', 'generate_image', 'update_memory',
]);

/** Build phase: creation + styling + scene management. */
const BUILD_PHASE_TOOLS = new Set([
  // Intelligence & pairing (available during build for mid-design lookups)
  'get_design_intelligence', 'suggest_font_pairing', 'generate_accessible_palette',
  // Creation
  'create_frame', 'create_text', 'create_rectangle', 'create_ellipse', 'create_image',
  'create_icon',
  // Batch
  'batch_execute', 'clone_with_overrides',
  // Styling (TC-1 consolidated + backward compat until TC-3)
  'set_style',
  'set_fill', 'set_stroke', 'set_effects', 'set_corner_radius', 'set_opacity', 'set_auto_layout',
  // Scene management (TC-1 consolidated + backward compat until TC-3)
  'transform_node',
  'move_node', 'resize_node', 'append_child', 'reorder_child', 'clone_node', 'delete_node',
  // Inspection
  'get_node_info', 'get_screenshot', 'scan_frame_structure',
  // Image + utility
  'generate_image', 'update_memory',
  // Quality
  'run_refinement_check',
  // Figma native (TC-1 consolidated + backward compat until TC-3)
  'read_figma_context', 'bind_variable',
  'apply_style',
  'apply_paint_style', 'apply_text_style', 'apply_effect_style',
  'create_figma_variables',
]);

export interface ToolResolverContext {
  toolsUsed: Set<string>;
  iteration: number;
}

export type ToolResolver = (ctx: ToolResolverContext) => ToolDefinition[];

/**
 * Returns a phase-aware tool resolver for chat mode.
 * - Plan phase (~14 tools): lookups + basic creation + scene queries
 * - Build phase (~17 tools): full creation + styling + scene management, no lookups
 * - Always excludes MCP-only tools (export, screenshot, refinement, variables, styles)
 */
export function chatToolResolver(): ToolResolver {
  // Pre-filter: remove chat-excluded tools once
  const chatTools = FIGMENTO_TOOLS.filter(t => !CHAT_EXCLUDED.has(t.name));
  const planTools = chatTools.filter(t => PLAN_PHASE_TOOLS.has(t.name));
  const buildTools = chatTools.filter(t => BUILD_PHASE_TOOLS.has(t.name));

  return (ctx: ToolResolverContext): ToolDefinition[] => {
    const inBuildPhase = [...ctx.toolsUsed].some(t => BUILD_PHASE_TRIGGERS.has(t));
    return inBuildPhase ? buildTools : planTools;
  };
}

/** Plugin-only tools (no MCP server equivalent) + local intelligence tools. */
const PLUGIN_ONLY_TOOLS: ToolDefinition[] = [
  {
    name: 'get_design_intelligence',
    description: 'CALL THIS FIRST before any design task. Returns the complete Figmento design playbook: workflow, taste rules, anti-patterns, typography/color selection, scoring criteria. This is mandatory context for producing top-tier designs. Only needs to be called once per design session.',
    input_schema: {
      type: 'object',
      properties: {},
    },
  },
  {
    name: 'suggest_font_pairing',
    description: 'Suggest complementary fonts for pairing from the bundled font knowledge base. Returns similar fonts (same mood family) and contrasting fonts (heading/body partners from proven pairings). Use when the user specifies ONE font and you need to find its best partner.',
    input_schema: {
      type: 'object',
      properties: {
        font: { type: 'string', description: 'The font family name to find pairings for (e.g. "Playfair Display", "Inter")' },
        mode: { type: 'string', description: 'contrast (different visual feel, best for heading/body pairs) | similar (same visual feel, same-family harmony) | both (default)' },
        count: { type: 'number', description: 'Number of suggestions to return per mode (default 5)' },
      },
      required: ['font'],
    },
  },
  {
    name: 'generate_accessible_palette',
    description: 'Generate a WCAG-compliant color palette from a base color. Uses pure-math contrast ratio calculations to guarantee accessibility. Returns light and dark mode variants with brand and neutral scales at specific contrast ratios (AA, AAA). Use when you need colors guaranteed to pass WCAG contrast checks.',
    input_schema: {
      type: 'object',
      properties: {
        base_color: { type: 'string', description: 'Base/brand color as hex (e.g. "#2680EB")' },
        background: { type: 'string', description: 'Background color as hex (default "#FFFFFF" for light, "#141414" for dark)' },
        mode: { type: 'string', description: 'light | dark | both (default both)' },
      },
      required: ['base_color'],
    },
  },
  {
    name: 'get_design_rules',
    description: 'Get detailed design rules and guidelines by category. Returns verbose reference material for typography, color, layout, print, evaluation, refinement, anti-patterns, gradients, taste, or saliency.',
    input_schema: {
      type: 'object',
      properties: {
        category: { type: 'string', description: 'Rule category: typography | color | layout | print | evaluation | refinement | anti-patterns | gradients | taste | saliency | all' },
      },
      required: ['category'],
    },
  },
  {
    name: 'analyze_canvas_context',
    description: 'Analyze existing frames on the Figma canvas to extract design context: dominant colors, typography, mood, and visual style. Call this when the user asks to "analyze the design", "use the project context", "match the existing style", or "generate an image that fits this design". Returns colors, text content, inferred mood, and a screenshot for visual reference.',
    input_schema: {
      type: 'object',
      properties: {
        nodeId: {
          type: 'string',
          description: 'Optional nodeId to analyze. If omitted, uses the current selection or first frame.',
        },
      },
    },
  },
  {
    name: 'update_memory',
    description: 'Save a design lesson, user preference, or rule to persistent memory. Use this when the user reports an issue, says "remember this", "always do X", "never do Y", or teaches you something about their preferences. Keep entries concise (one sentence).',
    input_schema: {
      type: 'object',
      properties: {
        entry: { type: 'string', description: 'Concise rule or lesson to remember (e.g., "Always use Outfit font for this brand", "User prefers dark themes")' },
      },
      required: ['entry'],
    },
  },
  {
    name: 'generate_image',
    description: 'Generate an image using AI (Gemini Imagen) and place it on the canvas. Provide a descriptive prompt for the image you want.',
    input_schema: {
      type: 'object',
      properties: {
        prompt: { type: 'string', description: 'Detailed description of the image to generate' },
        name: { type: 'string', description: 'Layer name for the image' },
        width: { type: 'number', description: 'Width to place the image (default: 400)' },
        height: { type: 'number', description: 'Height to place the image (default: 400)' },
        x: { type: 'number' },
        y: { type: 'number' },
        parentId: { type: 'string', description: 'Parent frame nodeId' },
      },
      required: ['prompt'],
    },
  },
];

export const FIGMENTO_TOOLS: ToolDefinition[] = [
  ...GENERATED_TOOLS,
  ...PLUGIN_ONLY_TOOLS,
];
