/**
 * Figmento Tool Definitions for Anthropic API tool_use format.
 * These mirror the MCP server tools but formatted as JSON Schema for the Messages API.
 * Excludes connect_to_figma and disconnect_from_figma (not needed inside the plugin).
 *
 * GENERATED_TOOLS (35 MCP tools) are auto-generated by scripts/generate-tool-schemas.ts.
 * Run `npm run build` (or the prebuild hook) to regenerate tools-schema.generated.ts.
 */

import { GENERATED_TOOLS } from './tools-schema.generated';

export interface ToolDefinition {
  name: string;
  description: string;
  input_schema: Record<string, unknown>;
}

const fillSchema = {
  type: 'object',
  properties: {
    type: { type: 'string', enum: ['SOLID', 'GRADIENT_LINEAR'] },
    color: { type: 'string', description: 'Hex color (e.g. "#FF5733")' },
    opacity: { type: 'number' },
    gradientStops: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          position: { type: 'number' },
          color: { type: 'string' },
          opacity: { type: 'number' },
        },
        required: ['position', 'color'],
      },
    },
    gradientDirection: {
      type: 'string',
      enum: ['left-right', 'right-left', 'top-bottom', 'bottom-top'],
      description: 'Gradient direction (default: top-bottom)',
    },
  },
  required: ['type'],
};

const cornerRadiusSchema = {
  oneOf: [
    { type: 'number' },
    { type: 'array', items: { type: 'number' }, minItems: 4, maxItems: 4 },
  ],
};

// ═══════════════════════════════════════════════════════════════
// PHASE-BASED TOOL FILTERING (Chat mode)
// ═══════════════════════════════════════════════════════════════

/** Tools never sent in chat mode — MCP-only or irrelevant for iterative chat. */
const CHAT_EXCLUDED = new Set([
  'export_node',
  'create_design',
]);

/** Lookup tools — needed in plan phase, removed once design starts. */
const LOOKUP_TOOLS = new Set([
  'get_layout_blueprint',
  'get_color_palette',
  'get_font_pairing',
  'get_size_preset',
]);

/** Tools that signal we've entered the build phase. */
const BUILD_PHASE_TRIGGERS = new Set([
  'create_frame',
  'create_text',
  'create_rectangle',
  'create_ellipse',
  'create_image',
  'set_fill',
  'set_auto_layout',
]);

/** Plan phase: lookups + basic creation + scene queries. */
const PLAN_PHASE_TOOLS = new Set([
  // Lookups
  'get_layout_blueprint', 'get_color_palette', 'get_font_pairing', 'get_size_preset',
  'get_contrast_check', 'get_design_rules',
  // Scene queries
  'get_selection', 'get_page_nodes', 'get_node_info', 'analyze_canvas_context',
  'scan_frame_structure', 'get_screenshot', 'read_figma_context',
  // Basic creation
  'create_frame', 'create_text', 'create_rectangle', 'create_ellipse',
  // Essential styling
  'set_fill',
  // Image + utility
  'create_image', 'generate_image', 'update_memory',
]);

/** Build phase: creation + styling + scene management. */
const BUILD_PHASE_TOOLS = new Set([
  // Creation
  'create_frame', 'create_text', 'create_rectangle', 'create_ellipse', 'create_image',
  'create_icon',
  // Styling
  'set_fill', 'set_stroke', 'set_effects', 'set_corner_radius', 'set_opacity', 'set_auto_layout',
  // Scene management
  'move_node', 'resize_node', 'append_child', 'reorder_child', 'clone_node', 'delete_node',
  // Inspection
  'get_node_info', 'get_screenshot', 'scan_frame_structure',
  // Image + utility
  'generate_image', 'update_memory',
  // Quality
  'run_refinement_check',
  // Figma native (variables, styles)
  'read_figma_context', 'bind_variable', 'apply_paint_style', 'apply_text_style', 'apply_effect_style',
  'create_figma_variables',
]);

export interface ToolResolverContext {
  toolsUsed: Set<string>;
  iteration: number;
}

export type ToolResolver = (ctx: ToolResolverContext) => ToolDefinition[];

/**
 * Returns a phase-aware tool resolver for chat mode.
 * - Plan phase (~14 tools): lookups + basic creation + scene queries
 * - Build phase (~17 tools): full creation + styling + scene management, no lookups
 * - Always excludes MCP-only tools (export, screenshot, refinement, variables, styles)
 */
export function chatToolResolver(): ToolResolver {
  // Pre-filter: remove chat-excluded tools once
  const chatTools = FIGMENTO_TOOLS.filter(t => !CHAT_EXCLUDED.has(t.name));
  const planTools = chatTools.filter(t => PLAN_PHASE_TOOLS.has(t.name));
  const buildTools = chatTools.filter(t => BUILD_PHASE_TOOLS.has(t.name));

  return (ctx: ToolResolverContext): ToolDefinition[] => {
    const inBuildPhase = [...ctx.toolsUsed].some(t => BUILD_PHASE_TRIGGERS.has(t));
    return inBuildPhase ? buildTools : planTools;
  };
}

/** Plugin-only tools (no MCP server equivalent). */
const PLUGIN_ONLY_TOOLS: ToolDefinition[] = [
  {
    name: 'analyze_canvas_context',
    description: 'Analyze existing frames on the Figma canvas to extract design context: dominant colors, typography, mood, and visual style. Call this when the user asks to "analyze the design", "use the project context", "match the existing style", or "generate an image that fits this design". Returns colors, text content, inferred mood, and a screenshot for visual reference.',
    input_schema: {
      type: 'object',
      properties: {
        nodeId: {
          type: 'string',
          description: 'Optional nodeId to analyze. If omitted, uses the current selection or first frame.',
        },
      },
    },
  },
  {
    name: 'update_memory',
    description: 'Save a design lesson, user preference, or rule to persistent memory. Use this when the user reports an issue, says "remember this", "always do X", "never do Y", or teaches you something about their preferences. Keep entries concise (one sentence).',
    input_schema: {
      type: 'object',
      properties: {
        entry: { type: 'string', description: 'Concise rule or lesson to remember (e.g., "Always use Outfit font for this brand", "User prefers dark themes")' },
      },
      required: ['entry'],
    },
  },
  {
    name: 'generate_image',
    description: 'Generate an image using AI (Gemini Imagen) and place it on the canvas. Provide a descriptive prompt for the image you want.',
    input_schema: {
      type: 'object',
      properties: {
        prompt: { type: 'string', description: 'Detailed description of the image to generate' },
        name: { type: 'string', description: 'Layer name for the image' },
        width: { type: 'number', description: 'Width to place the image (default: 400)' },
        height: { type: 'number', description: 'Height to place the image (default: 400)' },
        x: { type: 'number' },
        y: { type: 'number' },
        parentId: { type: 'string', description: 'Parent frame nodeId' },
      },
      required: ['prompt'],
    },
  },
];

export const FIGMENTO_TOOLS: ToolDefinition[] = [
  ...GENERATED_TOOLS,
  ...PLUGIN_ONLY_TOOLS,
];
