/**
 * Main code generator: converts BatchCommand[] → Plugin API JavaScript for use_figma.
 */

import { detectNeededHelpers } from './helpers';
import { TEMPLATES } from './templates';
import type { BatchCommand } from '../batch';

export type CodegenCommand = BatchCommand;

const MAX_CODE_SIZE = 45_000; // 45KB, leaving 5KB margin within use_figma's 50KB limit
const CREATION_ACTIONS = new Set([
  'create_frame', 'create_text', 'create_rectangle', 'create_ellipse',
  'create_vector', 'create_component', 'group_nodes', 'clone_node', 'find_nodes',
]);

/**
 * Generate Plugin API JavaScript from an array of Figma commands.
 * The output is a complete, self-contained async IIFE that can be passed to use_figma.
 */
export function generateFigmaCode(commands: CodegenCommand[]): string {
  const tempIdToVar = new Map<string, string>();
  let varCounter = 0;

  // Detect and include needed helpers
  const helpers = detectNeededHelpers(commands);

  const blocks: string[] = [];
  blocks.push('// Generated by Figmento Code Generator');
  blocks.push('const results = [];');
  blocks.push('');

  for (const cmd of commands) {
    const template = TEMPLATES[cmd.action];
    if (!template) {
      blocks.push(`// Unsupported action: ${cmd.action}`);
      blocks.push(`results.push({ action: ${JSON.stringify(cmd.action)}, success: false, error: 'Unsupported action' });`);
      continue;
    }

    const varName = `node_${varCounter++}`;
    if (cmd.tempId) {
      tempIdToVar.set(cmd.tempId, varName);
    }

    // Resolve $tempId references in params
    const resolvedParams = resolveRefs(cmd.params, tempIdToVar);

    // Resolve parentId: if it's a $ref, use the variable name directly
    let parentVar: string | undefined;
    if (resolvedParams.parentId && typeof resolvedParams.parentId === 'string') {
      if (resolvedParams.parentId.startsWith('$')) {
        const refKey = resolvedParams.parentId.slice(1);
        parentVar = tempIdToVar.get(refKey);
      }
      // If not a $ref, parentVar stays undefined — template handles nodeId lookup
    }

    // For non-creation actions on existing nodes, resolve the node
    let nodeResolution = '';
    if (!CREATION_ACTIONS.has(cmd.action) && resolvedParams.nodeId) {
      const nodeId = resolvedParams.nodeId as string;
      if (nodeId.startsWith('$')) {
        // Already a variable reference — reuse it
        const refKey = nodeId.slice(1);
        const existingVar = tempIdToVar.get(refKey);
        if (existingVar) {
          // Redefine varName to point to existing node
          blocks.push(`// ${cmd.action}${cmd.tempId ? ` (tempId: ${cmd.tempId})` : ''}`);
          blocks.push(`try {`);
          blocks.push(`  ${template(resolvedParams, existingVar, parentVar)}`);
          blocks.push(`  results.push({ ${cmd.tempId ? `tempId: ${JSON.stringify(cmd.tempId)}, ` : ''}action: ${JSON.stringify(cmd.action)}, success: true });`);
          blocks.push(`} catch (e) {`);
          blocks.push(`  results.push({ ${cmd.tempId ? `tempId: ${JSON.stringify(cmd.tempId)}, ` : ''}action: ${JSON.stringify(cmd.action)}, success: false, error: e.message });`);
          blocks.push(`}`);
          blocks.push('');
          continue;
        }
      }
      // Real Figma node ID — need to look it up
      nodeResolution = `const ${varName} = figma.getNodeById(${JSON.stringify(nodeId)});`;
    }

    // Generate the try/catch block
    blocks.push(`// ${cmd.action}${cmd.tempId ? ` (tempId: ${cmd.tempId})` : ''}`);
    blocks.push(`try {`);
    if (nodeResolution) blocks.push(`  ${nodeResolution}`);
    blocks.push(`  ${template(resolvedParams, varName, parentVar)}`);
    if (CREATION_ACTIONS.has(cmd.action)) {
      blocks.push(`  results.push({ ${cmd.tempId ? `tempId: ${JSON.stringify(cmd.tempId)}, ` : ''}action: ${JSON.stringify(cmd.action)}, nodeId: ${varName}.id, success: true });`);
    } else {
      blocks.push(`  results.push({ ${cmd.tempId ? `tempId: ${JSON.stringify(cmd.tempId)}, ` : ''}action: ${JSON.stringify(cmd.action)}, success: true });`);
    }
    blocks.push(`} catch (e) {`);
    blocks.push(`  results.push({ ${cmd.tempId ? `tempId: ${JSON.stringify(cmd.tempId)}, ` : ''}action: ${JSON.stringify(cmd.action)}, success: false, error: e.message });`);
    blocks.push(`}`);
    blocks.push('');
  }

  // Footer: select root node and return results
  const firstCreation = commands.find(c => CREATION_ACTIONS.has(c.action));
  if (firstCreation?.tempId) {
    const rootVar = tempIdToVar.get(firstCreation.tempId);
    if (rootVar) {
      blocks.push(`// Select and zoom to root`);
      blocks.push(`if (${rootVar}) {`);
      blocks.push(`  figma.currentPage.selection = [${rootVar}];`);
      blocks.push(`  figma.viewport.scrollAndZoomIntoView([${rootVar}]);`);
      blocks.push(`}`);
    }
  }

  blocks.push('');
  blocks.push(`return JSON.stringify({ results, total: ${commands.length}, succeeded: results.filter(r => r.success).length });`);

  // Assemble final code
  const helpersBlock = helpers.length > 0 ? helpers.join('\n\n') + '\n\n' : '';
  const code = helpersBlock + blocks.join('\n');

  // Size check
  if (code.length > MAX_CODE_SIZE) {
    throw new Error(
      `Generated code is ${code.length} chars (limit: ${MAX_CODE_SIZE}). ` +
      `Split into multiple generate_figma_code calls with fewer commands.`
    );
  }

  return code;
}

/**
 * Deep-resolve $tempId references in params.
 * $root → looks up in tempIdToVar map but keeps as string for the template to handle.
 */
function resolveRefs(
  params: Record<string, unknown>,
  _map: Map<string, string>,
): Record<string, unknown> {
  // Return params as-is — templates handle $ref resolution via parentVar parameter
  // Only string values starting with $ are ref markers
  return params;
}
